version: '2.1'

services:

  base-app:
    build:
      context: .
    volumes:
      - .:/code
    environment:
      NODE_ENV: ${NODE_ENV}
      JSON_FILE_URL: https://nhsukpharmacydataetl.blob.core.windows.net/etl-output/pharmacy-data.json
      MONGO_HOST: mongo
      MONGO_PORT: ${MONGO_PORT}
      DB_CONFIG: pharmacy
      UPDATE_SCHEDULE: ${UPDATE_SCHEDULE}

  mongodb-updater:
    extends:
      service: base-app
    volumes:
      - mongodb-updater-node_modules:/code/node_modules
    links:
    - mongo-db:mongo

  mongo-db:
    image: mongo:3.4
    ports:
      - 27017:27017

volumes:
  mongodb-updater-node_modules:
