version: '2.1'

services:

  test:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run test-watch
    volumes:
      - mongodb-updater-tests-node_modules:/code/node_modules
    environment:
      NODE_ENV: test
      KEY_FOR_MONGO_ID: name
    links:
    - mongo-db:mongo

  check-coverage:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn coverage-check
    volumes:
      - mongodb-updater-tests-node_modules:/code/node_modules
    environment:
      NODE_ENV: test
    links:
    - mongo-db:mongo

  test-ci:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run test-ci
    user: root
    volumes:
      - mongodb-updater-tests-node_modules:/code/node_modules
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      NODE_ENV: test
      KEY_FOR_MONGO_ID: name
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
    links:
    - mongo-db:mongo

  mongo-db:
    image: mongo:3.4
    ports:
      - 27017:27017

volumes:
  mongodb-updater-tests-node_modules:
