version: '2'
services:

  mongodb-updater-pharmacy:
    image: nhsuk/mongodb-updater:${DOCKER_IMAGE_TAG}
    environment:
      NODE_ENV: ${NODE_ENV}
      JSON_FILE_URL: ${JSON_FILE_URL_PHARMACY}
      DB_CONFIG: ${DB_CONFIG_PHARMACY}
      MONGO_HOST: ${MONGO_HOST_PHARMACY}
      MONGO_PORT: ${MONGO_PORT_PHARMACY}
      CHANGE_THRESHOLD: ${CHANGE_THRESHOLD_PHARMACY}
      UPDATE_SCHEDULE: ${UPDATE_SCHEDULE_PHARMACY}
    labels:
      io.rancher.container.pull_image: always
    logging:
      driver: splunk
      options:
        splunk-url: ${SPLUNK_HEC_URL}
        splunk-token: ${SPLUNK_HEC_TOKEN}
        splunk-insecureskipverify: "true"
        splunk-sourcetype: docker
        splunk-source: mongodb-updater-pharmacy
        splunk-verify-connection: "false"
        tag: "{{`{{.ImageName}} {{.Name}} {{.FullID}}`}}"
        splunk-format: json

  mongodb-updater-profiles:
    image: nhsuk/mongodb-updater:${DOCKER_IMAGE_TAG}
    environment:
      NODE_ENV: ${NODE_ENV}
      JSON_FILE_URL: ${JSON_FILE_URL_PROFILES}
      DB_CONFIG:  ${DB_CONFIG_PROFILES}
      MONGO_HOST: ${MONGO_HOST_PROFILES}
      MONGO_PORT: ${MONGO_PORT_PROFILES}
      CHANGE_THRESHOLD: ${CHANGE_THRESHOLD_PROFILES}
      UPDATE_SCHEDULE: ${UPDATE_SCHEDULE_PROFILES}
    labels:
      io.rancher.container.pull_image: always
    logging:
      driver: splunk
      options:
        splunk-url: ${SPLUNK_HEC_URL}
        splunk-token: ${SPLUNK_HEC_TOKEN}
        splunk-insecureskipverify: "true"
        splunk-sourcetype: docker
        splunk-source: mongodb-updater-profiles
        splunk-verify-connection: "false"
        tag: "{{`{{.ImageName}} {{.Name}} {{.FullID}}`}}"
        splunk-format: json
